# Generated by Django 4.2.4 on 2023-08-18 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits.')]),
        ),
    ]
