# Generated by Django 3.2.12 on 2023-08-08 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shoppingitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
