# Generated by Django 3.2.12 on 2023-08-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20230808_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='description',
            field=models.TextField(),
        ),
    ]
