# Generated by Django 3.2.12 on 2023-08-08 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_shoppingitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
