# Generated by Django 3.2.12 on 2023-08-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_alter_shoppingitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
