# Generated by Django 3.2.12 on 2023-08-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_alter_shoppingitem_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shoppingItem',
            new_name='shoppingItemModel',
        ),
    ]
