# Generated by Django 3.2.12 on 2023-08-10 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_rename_shoppingitem_shoppingitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
